/* SYNTHETIC DEMO DATA (?demo=1). Every person, student, number and date here is made up.
   555-01xx numbers are reserved for fiction. Nothing in demo mode talks to any server. */
window.TTGR_DEMO = function () {
  function d(off, hm) { var x = new Date(); x.setDate(x.getDate() + off); var s = x.getFullYear() + '-' + ('0' + (x.getMonth() + 1)).slice(-2) + '-' + ('0' + x.getDate()).slice(-2); return hm ? s + 'T' + hm : s; }
  /* Interview times never land on Shabbat or Friday afternoon. */
  function wd(off, hm) { var x = new Date(); x.setDate(x.getDate() + off); var step = off < 0 ? -1 : 1; while (x.getDay() === 6 || (x.getDay() === 5 && hm >= '12:00')) x.setDate(x.getDate() + step);
    return x.getFullYear() + '-' + ('0' + (x.getMonth() + 1)).slice(-2) + '-' + ('0' + x.getDate()).slice(-2) + 'T' + hm; }
  var musts = function (o) { return JSON.stringify(o); };
  return {
    line: '(555) 010-0199',
    needs: [
      { id: 'n1', code: 'Q12', role: 'RBT', student: 'Milo', borough: 'Queens', area: 'Jamaica', days: 'Mon\u2013Thu', from: '15:00', to: '19:00', start: d(10), hrs_week: 16, notes: '', status: 'posted', jd: '', posted: JSON.stringify({ indeed: d(-6, '10:00'), community: d(-5, '09:00') }), created: d(-19, '09:00') },
      { id: 'n2', code: 'K41', role: 'SETSS', student: 'Ava', borough: 'Brooklyn', days: 'Tue, Thu', from: '16:00', to: '18:00', start: d(14), hrs_week: 4, notes: 'SWD 1\u20136', status: 'open', jd: '', posted: '{}', created: d(-2, '09:00') },
      { id: 'n3', code: 'M27', role: 'BCBA', student: 'Leah', borough: 'Manhattan', days: 'Tue\u2013Thu', from: '14:00', to: '18:00', start: d(21), hrs_week: 4, notes: 'supervision', status: 'posted', jd: '', posted: JSON.stringify({ aba: d(-8, '10:00'), linkedin: d(-8, '10:05') }), created: d(-9, '09:00') },
      { id: 'n4', code: 'S18', role: 'OT', student: 'Eli', borough: 'Staten Island', days: 'Fri', from: '13:00', to: '15:00', start: d(7), hrs_week: 2, notes: '', status: 'filled', jd: '', posted: JSON.stringify({ indeed: d(-7, '10:00') }), created: d(-31, '09:00') },
      { id: 'n5', code: 'X33', role: 'Para', student: 'Noa', borough: 'Bronx', area: 'Riverdale', days: 'Mon\u2013Fri', from: '08:00', to: '14:30', start: d(30), hrs_week: 32.5, notes: '', status: 'paused', jd: '', posted: JSON.stringify({ indeed: d(-11, '10:00') }), created: d(-12, '09:00') },
      { id: 'n6', code: 'K58', role: 'SLP', student: 'Ezra', borough: 'Brooklyn', area: 'Midwood', days: 'Mon, Wed', from: '15:00', to: '17:00', start: d(12), hrs_week: 4, notes: 'Bilingual a plus', status: 'posted', jd: '', posted: JSON.stringify({ linkedin: d(-5, '11:00'), indeed: d(-5, '11:10') }), created: d(-6, '09:00') },
      { id: 'n7', code: 'Q05', role: 'RBT', student: 'Ari', borough: 'Queens', area: 'Flushing', days: 'Sun\u2013Thu', from: '16:00', to: '19:00', start: d(3), hrs_week: 15, notes: '', status: 'filled', jd: '', posted: JSON.stringify({ indeed: d(-25, '10:00'), college: d(-25, '10:05') }), created: d(-26, '09:00') }
    ],
    people: [
      { id: 'p1', name: 'Jordan Avery', phone: '(555) 010-0141', email: 'jordan@example.com', role: 'RBT', boroughs: 'Queens, Brooklyn', availability: 'Mon\u2013Thu 2\u20138pm', credential: 'RBT', cred_status: 'verified', cred_link: '', resume_url: 'https://example.com/resume-jordan.pdf', source: 'Phone screen \u00b7 flyer Q12', need_code: 'Q12', fit_summary: '3 yrs 1:1 ABA. Cut elopement from daily to weekly with a first/then board. Can start in 10 days.', musts: musts({ hours: true }), stage: 'applicant', created: d(-1, '20:42') },
      { id: 'p2', name: 'Priya Nandakumar', phone: '(555) 010-0152', email: 'priya@example.com', role: 'RBT', boroughs: 'Queens', availability: 'Mon\u2013Fri 3\u20137pm', credential: 'RBT', cred_status: 'verified', resume_url: 'https://example.com/resume-priya.pdf', source: 'Indeed', need_code: 'Q12', fit_summary: '2 yrs DTT/NET with preschoolers. Taught AAC break requests. Available all 4 days.', musts: musts({ hours: true }), stage: 'interview', decided_at: d(-1, '08:55'), created: d(-2, '21:15') },
      { id: 'p3', name: 'Marcus Lee', phone: '(555) 010-0163', email: 'marcus@example.com', role: 'Behavior tech', boroughs: 'Queens, Manhattan', availability: 'Mon\u2013Thu 4\u20138pm', credential: 'RBT in progress', cred_status: 'not_found', resume_url: '', source: 'Past applicant', need_code: 'Q12', fit_summary: '1:1 aide for a 7th grader. 40-hour training done, competency not yet.', musts: musts({ hours: false }), stage: 'applicant', created: d(-3, '18:00') },
      { id: 'p4', name: 'Dana Whitfield', phone: '(555) 010-0174', email: 'dana@example.com', role: 'BCBA', boroughs: 'Manhattan, Bronx', availability: 'Tue\u2013Thu 1\u20136pm', credential: 'BCBA + LBA', cred_status: 'unchecked', resume_url: 'https://example.com/resume-dana.pdf', source: 'ABA job board', need_code: 'M27', fit_summary: '6 yrs, school consults, supervises 4 RBTs. Says NY LBA active; not yet checked.', musts: musts({ hours: true }), stage: 'applicant', created: d(-1, '13:10') },
      { id: 'p5', name: 'Sofia Ramirez', phone: '(555) 010-0185', email: 'sofia@example.com', role: 'RBT', boroughs: 'Queens', availability: 'Mon\u2013Thu 3\u20137pm', credential: 'RBT', cred_status: 'verified', resume_url: 'https://example.com/resume-sofia.pdf', source: 'Referral', need_code: 'Q12', fit_summary: 'Bilingual (Spanish). 4 yrs home ABA. Strong data habits.', musts: musts({ hours: true }), stage: 'interview', decided_at: d(-3, '09:00'), created: d(-5, '10:00') },
      { id: 'p6', name: 'Sam Ortiz', phone: '(555) 010-0196', email: 'sam@example.com', role: 'OT', boroughs: 'Staten Island, Brooklyn', availability: 'Fri 12\u20135pm', credential: 'NYS OT license', cred_status: 'verified', resume_url: 'https://example.com/resume-sam.pdf', source: 'Indeed', need_code: 'S18', fit_summary: 'Pediatric OT, 5 yrs. Sensory integration certificate.', musts: musts({ hours: true }), stage: 'hired', decided_at: d(-1, '15:20'), created: d(-6, '10:00') },
      { id: 'p9', name: 'Nadia Brooks', phone: '(555) 010-0128', email: 'nadia@example.com', role: 'RBT', boroughs: 'Queens', availability: 'Mon\u2013Thu 2\u20137pm', credential: 'RBT', cred_status: 'verified', cred_checked: d(-4, '12:00'), resume_url: 'https://example.com/resume-nadia.pdf', source: 'Handshake', need_code: 'Q12', fit_summary: '3 yrs clinic ABA, strong on parent-free sessions and data. Lives 10 minutes from Jamaica.', musts: musts({ hours: true }), stage: 'offer', decided_at: d(-1, '17:05'), created: d(-8, '09:30') },
      { id: 'p10', name: 'Owen Patel', phone: '(555) 010-0139', email: 'owen@example.com', role: 'RBT', boroughs: 'Queens', availability: 'Sun\u2013Thu 3\u20138pm', credential: 'RBT', cred_status: 'verified', cred_checked: d(-15, '12:00'), resume_url: 'https://example.com/resume-owen.pdf', source: 'Indeed', need_code: 'Q05', fit_summary: '2 yrs home ABA. Calm, reliable, great notes.', musts: musts({ hours: true }), stage: 'welcome', decided_at: d(-2, '10:15'), start_date: d(3), timesheet_at: '', created: d(-20, '19:00') },
      { id: 'p11', name: 'Grace Okafor', phone: '(555) 010-0146', email: 'grace@example.com', role: 'SLP', boroughs: 'Brooklyn', availability: 'Mon, Wed after 2pm', credential: 'NYS SLP + TSSLD', cred_status: 'verified', cred_checked: d(-2, '12:00'), resume_url: 'https://example.com/resume-grace.pdf', source: 'LinkedIn', need_code: 'K58', fit_summary: 'School-based SLP, 6 yrs. AAC experience. Speaks Yoruba and English.', musts: musts({ hours: true }), stage: 'interview', decided_at: d(-2, '12:30'), created: d(-4, '08:00') },
      { id: 'p12', name: 'Ben Carter', phone: '(555) 010-0157', email: 'ben@example.com', role: 'RBT', boroughs: 'Manhattan', availability: 'Evenings', credential: 'None yet', cred_status: 'not_found', resume_url: '', source: 'Indeed', need_code: 'Q12', fit_summary: 'No RBT yet; lives far from Queens.', musts: musts({ hours: false }), stage: 'pass', decided_at: d(-3, '14:00'), created: d(-6, '09:00') },
      { id: 'p13', name: 'Mia Rossi', phone: '(555) 010-0168', email: 'mia@example.com', role: 'BCBA', boroughs: 'Manhattan', availability: 'Tue\u2013Thu 1\u20135pm', credential: 'BCBA', cred_status: 'unchecked', resume_url: 'https://example.com/resume-mia.pdf', source: 'ABA job board', need_code: 'M27', fit_summary: 'BCBA 2 yrs; NY LBA pending. Strong school consults.', musts: musts({ hours: true }), stage: 'maybe', decided_at: d(-2, '16:00'), created: d(-5, '11:00') },
      { id: 'p14', name: 'Tom Fischer', phone: '(555) 010-0179', email: 'tom@example.com', role: 'Para', boroughs: 'Bronx', availability: 'School days', credential: 'TA certificate', cred_status: 'unchecked', resume_url: '', source: 'Indeed', need_code: 'X33', fit_summary: 'Para in a District 75 class for 3 years.', musts: musts({ hours: true }), stage: 'applicant', created: d(-10, '10:00') },
      { id: 'p8', name: 'Alexandra Konstantinopoulos-Whitaker', phone: '', email: 'alex.k@example.com', role: 'RBT', boroughs: 'Queens', availability: 'Weekdays after 2pm', credential: 'RBT, BCBA coursework in progress', cred_status: 'unchecked', resume_url: 'https://example.com/resume-alex.pdf', source: 'Email', need_code: 'Q12', fit_summary: 'Replied to the Q12 post with a resume. 5 yrs school-based ABA.', musts: musts({}), stage: 'review', created: d(0, '08:10') },
      { id: 'p7', name: 'Kim Osei', phone: '(555) 010-0117', email: 'kim@example.com', role: 'RBT', boroughs: 'Bronx', availability: 'Weekends', credential: 'RBT', cred_status: 'verified', resume_url: '', source: 'Indeed', need_code: 'Q12', fit_summary: 'Bronx only, weekends only.', musts: musts({ hours: false }), stage: 'applicant', created: d(-4, '10:00') }
    ],
    interviews: [
      { id: 'i1', person_id: 'p2', need_code: 'Q12', when: '', status: 'to_schedule', consent: '', summary: '', created: d(-1, '09:00') },
      { id: 'i2', person_id: 'p5', need_code: 'Q12', when: wd(-1, '10:30'), status: 'done', consent: 'yes', updated: wd(-1, '11:10'),
        summary: JSON.stringify({ summary: 'Warm, specific answers. Clear on data collection and on calling the BCBA when a plan isn\u2019t working.', credentials: 'RBT active (checked on BACB).', experience: '4 yrs home ABA, ages 4\u201312; manding, toileting, transitions.', availability: 'Mon\u2013Thu 3\u20137pm confirmed; can start in 10 days.', strengths: 'Bilingual; strong with families; tidy notes.', concerns: 'Has not worked in a school building yet.', follow_ups: 'Wants to meet the BCBA before starting.', recording: 'saved in Bland' }) },
      { id: 'i3', person_id: 'p9', need_code: 'Q12', when: wd(-3, '11:00'), status: 'done', consent: '', updated: wd(-3, '11:40'), summary: JSON.stringify({ summary: 'Great fit. Knows the plan-to-session routine cold. Asked good questions about supervision.', by: 'you' }) },
      { id: 'i4', person_id: 'p11', need_code: 'K58', when: wd(1, '10:30'), status: 'scheduled', consent: '', summary: '', updated: d(-1, '13:00') },
      { id: 'i5', person_id: 'p10', need_code: 'Q05', when: wd(-6, '10:00'), status: 'done', consent: '', updated: wd(-6, '10:40'), summary: JSON.stringify({ summary: 'Reliable, calm, flexible on Sundays.', by: 'you' }) },
      { id: 'i6', person_id: 'p6', need_code: 'S18', when: wd(-4, '11:00'), status: 'done', consent: '', updated: wd(-4, '11:30'), summary: JSON.stringify({ summary: 'Strong sensory work; Friday afternoons are fine for them.', by: 'you' }) }
    ],
    queue: [
      { id: 'q1', at: d(-1, '09:00'), kind: 'call_schedule', person_id: 'p2', need_code: 'Q12', payload: '{}', status: 'waiting_approval', result: '' },
      { id: 'q2', at: d(-3, '10:20'), kind: 'draft_welcome', person_id: 'p10', need_code: 'Q05', payload: '{}', status: 'done', done_at: d(-3, '10:30'), result: 'https://mail.google.com/mail/u/0/#drafts' },
      { id: 'q3', at: d(-2, '12:35'), kind: 'draft_invite', person_id: 'p11', need_code: 'K58', payload: '{}', status: 'done', done_at: d(-2, '13:00'), result: 'https://mail.google.com/mail/u/0/#drafts' }
    ],
    settings: { apply_email: 'jobs@example.org', calling: 'off', pay_default: '', friday_cutoff: '12:00' },
    freeTimes: [
      { start: d(3, '10:00'), end: d(3, '10:30'), label: '' },
      { start: d(4, '16:30'), end: d(4, '17:00'), label: '' },
      { start: d(5, '12:00'), end: d(5, '12:30'), label: '' }
    ],
    dismissed: []
  };
};
